name: Check and Update .env.example on PR

on:
  pull_request:
    branches:
      - main

jobs:
  check-update-env-example:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git User Identity
        run: |
          git config --global user.email "erdemkosk@gmail.com"
          git config --global user.name "Erdem Köşk"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v8

      - name: Get Current Directory
        run: |
          current_directory=$(pwd)
          echo "Current Directory: $current_directory"

          # .env.example dosyasını kontrol et veya oluştur
          if [ ! -f "$current_directory/.env.example" ]; then
            touch "$current_directory/.env.example"
          fi

          # .env.example dosyasının bulunması gereken dizini belirtin (dizin adını değiştirmeniz gerekiyor)
          env_example_dir="$current_directory"

          # Değiştirilen dosyaları al
          changed_files="${{ steps.changed-files.outputs.all }}"
          
          # Değiştirilen dosyalarda process.env değerlerini ara
          for file in $changed_files; do
            file_content=$(<"$env_example_dir/$file")
            process_env_values=$(echo "$file_content" | grep -Eo 'process\.env\.[A-Za-z_][A-Za-z_0-9]*')

            for value in $process_env_values; do
              # Değer .env.example dosyasında eksikse veya farklısa, .env.example dosyasını güncelle
              if ! grep -q "$value" "$env_example_dir/.env.example"; then
                sed -i "/$value/c$value=<default_value>" "$env_example_dir/.env.example"
              fi
            done
          done

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git -C "$env_example_dir" status --porcelain)" ]; then
            git -C "$env_example_dir" add "$env_example_dir/.env.example"
            git -C "$env_example_dir" commit -m "Update .env.example"
            git -C "$env_example_dir" push origin ${{ github.event.pull_request.head.ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
