name: Check and Update .env.example on PR

on:
  pull_request:
    branches:
      - main

jobs:
  check-update-env-example:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git User Identity
        run: |
          git config --global user.email "erdemkosk@gmail.com"
          git config --global user.name "Erdem Köşk"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v8

      - name: Get Current Directory
        run: |
          current_directory=$(pwd)
          echo "Current Directory: $current_directory"

          # .env.example dosyasını kontrol et veya oluştur
          if [ ! -f ".env.example" ]; then
            touch ".env.example"
          fi

          # Değiştirilen dosyaları al
          changed_files="${{ steps.changed-files.outputs.all }}"
          
          # Değiştirilen dosyalarda process.env değerlerini ara
          for file in $changed_files; do
            file_content=$(<"$current_directory/$file")
            process_env_values=$(echo "$file_content" | grep -Eo 'process\.env\.[A-Za-z_][A-Za-z_0-9]*')

            for value in $process_env_values; do
              # Değer .env.example dosyasında eksikse veya farklısa, .env.example dosyasını güncelle
              if ! grep -q "$value" ".env.example"; then
                sed -i "/$value/c$value=<default_value>" ".env.example"
              fi
            done
          done

      - name: Create and Checkout a New Branch
        run: |
          git checkout -b temp-branch
        continue-on-error: true

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add ".env.example"
            git commit -m "Update .env.example"
            git push origin temp-branch
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
