name: Check and Update .env.example on PR

on:
  pull_request:
    branches:
      - main

jobs:
  check-update-env-example:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git User Identity
        run: |
          git config --global user.email "erdemkosk@gmail.com"
          git config --global user.name "Erdem Köşk"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Current Directory
        run: |
          current_directory=$(pwd)
          echo "Current Directory: $current_directory"

          # .env.example dosyasını kontrol et veya oluştur
          if [ ! -f "$current_directory/.env.example" ]; then
            touch "$current_directory/.env.example"
          fi

          # PR içeriğindeki dosyaları işle
          pr_diff=$(git diff --name-only HEAD^)

          # PR içeriğindeki dosyalarda process.env değerlerini ara
          for file in $pr_diff; do
            file_content=$(<"$current_directory/$file")
            process_env_values=$(echo "$file_content" | grep -Eo 'process\.env\.[A-Za-z_][A-Za-z_0-9]*')

            for value in $process_env_values; do
              # Değer .env.example dosyasında eksikse veya farklısa, .env.example dosyasını güncelle
              if ! grep -q "$value" "$current_directory/.env.example"; then
                sed -i "/$value/c$value=<default_value>" "$current_directory/.env.example"
              fi
            done
          done

      - name: Commit and Push Changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add "$current_directory/.env.example"
            git commit -m "Update .env.example"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
